const mongoose = require("mongoose");

const userSchema = new mongoose.Schema({
  patientId: { type: String, required: true, unique: true },
  name: { type: String },
  fatherOrHusbandName: { type: String },
  occupation: { type: String },
  phoneNumber: { type: String },
  age: { type: String },
  mobileNumber: { type: String },
  email: { type: String },
  chiefComplaints: { type: String },
  modelities: { type: String },
  intelligence: { type: String },
  memory: { type: String },
  reaction: { type: String },
  desires: { type: String },
  aversions: { type: String },
  dreams: { type: String },
  salt: { type: String },
  sweet: { type: String },
  butter: { type: String },
  sleepiwithside: { type: String },
  spice: { type: String },
  sour: { type: String },
  ghee: { type: String },
  fruits: { type: String },
  milk: { type: String },
  egg: { type: String },
  nonveg: { type: String },
  vegetables: { type: String },
  thermals: { type: String },
  stools: { type: String },
  urine: { type: String },
  sweat: { type: String },
  gpe:{ type: String },
  pulse:{ type: String },
  nails:{ type: String },
  weight:{ type: String },
  extras:{ type: String },
  diagnosis:{ type: String }
});

module.exports = mongoose.model("patients", userSchema);
